version: '3'
services:
  mypostgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: users_db
      POSTGRES_USER: admin
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  myapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mypostgres
    networks:
      - mynetwork
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/users_db
networks:
  mynetwork:
    driver: bridge