apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  ports:
  - port: 8080 #port for auth-service 
    protocol: TCP
    name: http
  selector:
    app: auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - image: dasha12678/auth-service:latest
        name: auth-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 #port for auth-service 
        env:
        - name: DB_HOST
          value: "jdbc:postgresql://${DB_HOST}"
        - name: DB_USER
          value: "${DB_USER}"
        - name: DB_PASSWORD
          value: "${DB_PASSWORD}"   
      restartPolicy: Always
    