apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  ports:
  - port: 8080 #port for auth-service 
    protocol: TCP
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: auth-service
        name: auth-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 #port for auth-service 
      restartPolicy: Always
