name: Continuous Deployment

on:
  push:
    branches:
      - "**"
  pull_request_target:
    types: [opened, synchronize, reopened] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "Hello from GitHub Actions!"