name: Build, Test, Push, Measure Coverage with Jacoco

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dasha12678/user-management-service:latest


  test_coverage:
    runs-on: ubuntu-latest
    needs: build_test_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK  
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Generate Jacoco Report
        run: mvn jacoco:report

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html

      - name: Verify coverage
        uses: actions/jacoco-report@v1 #?action to parse the coverage report and verify the coverage?
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.TOKEN }}
          min-coverage-overall: 80
